//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.Client.WPF.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominoAllFives.Client.WPF.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string ChangePassword_btnChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword_btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string ChangePassword_lblNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string CreateGame_btnCreate {
            get {
                return ResourceManager.GetString("CreateGame_btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de jugadores.
        /// </summary>
        public static string CreateGame_lblNumberOfPlayers {
            get {
                return ResourceManager.GetString("CreateGame_lblNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu partida.
        /// </summary>
        public static string CreateGame_lblTitle {
            get {
                return ResourceManager.GetString("CreateGame_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación ganadora.
        /// </summary>
        public static string CreateGame_lblWinningScore {
            get {
                return ResourceManager.GetString("CreateGame_lblWinningScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string DeleteAccount_lblCurrentPassword {
            get {
                return ResourceManager.GetString("DeleteAccount_lblCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al confirmar, ya no podrás ingresar con esta cuenta ni acceder a las partidas y puntuaciones que generaste.
        /// </summary>
        public static string DeleteAccount_lblDeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccount_lblDeleteAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string EditProfile_btnSaveChanges {
            get {
                return ResourceManager.GetString("EditProfile_btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string EditProfile_lblTitle {
            get {
                return ResourceManager.GetString("EditProfile_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar amigos.
        /// </summary>
        public static string Friends_btnAddFriends {
            get {
                return ResourceManager.GetString("Friends_btnAddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string Friends_btnDeclineRequest {
            get {
                return ResourceManager.GetString("Friends_btnDeclineRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string Friends_btnFriendList {
            get {
                return ResourceManager.GetString("Friends_btnFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar amigo.
        /// </summary>
        public static string Friends_btnRemoveFriend {
            get {
                return ResourceManager.GetString("Friends_btnRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad.
        /// </summary>
        public static string Friends_btnRequests {
            get {
                return ResourceManager.GetString("Friends_btnRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has recibido solicitudes de amistad.
        /// </summary>
        public static string Friends_lblNoReceivedFriendRequests {
            get {
                return ResourceManager.GetString("Friends_lblNoReceivedFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes solicitudes de amistad enviadas pendientes.
        /// </summary>
        public static string Friends_lblNoSentFriendRequests {
            get {
                return ResourceManager.GetString("Friends_lblNoSentFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador no fue encontrado.
        /// </summary>
        public static string Friends_lblPlayerNotFound {
            get {
                return ResourceManager.GetString("Friends_lblPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad recibidas.
        /// </summary>
        public static string Friends_lblReceivedRequests {
            get {
                return ResourceManager.GetString("Friends_lblReceivedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes enviadas.
        /// </summary>
        public static string Friends_lblSentRequests {
            get {
                return ResourceManager.GetString("Friends_lblSentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string Friends_lblTitle {
            get {
                return ResourceManager.GetString("Friends_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pozo.
        /// </summary>
        public static string GameBoard_btnBoneyard {
            get {
                return ResourceManager.GetString("GameBoard_btnBoneyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasar.
        /// </summary>
        public static string GameBoard_btnPass {
            get {
                return ResourceManager.GetString("GameBoard_btnPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar partida.
        /// </summary>
        public static string GameBoard_btnReportGame {
            get {
                return ResourceManager.GetString("GameBoard_btnReportGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta.
        /// </summary>
        public static string GameBoard_lblGoal {
            get {
                return ResourceManager.GetString("GameBoard_lblGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Global_btnAccept {
            get {
                return ResourceManager.GetString("Global_btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Global_btnBack {
            get {
                return ResourceManager.GetString("Global_btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Global_btnCancel {
            get {
                return ResourceManager.GetString("Global_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Global_btnClose {
            get {
                return ResourceManager.GetString("Global_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descartar cambios.
        /// </summary>
        public static string Global_btnDiscard {
            get {
                return ResourceManager.GetString("Global_btnDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Global_btnLogin {
            get {
                return ResourceManager.GetString("Global_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver repetición de partida.
        /// </summary>
        public static string Global_btnMatchReplay {
            get {
                return ResourceManager.GetString("Global_btnMatchReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atender.
        /// </summary>
        public static string Global_btnResolve {
            get {
                return ResourceManager.GetString("Global_btnResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Global_btnSave {
            get {
                return ResourceManager.GetString("Global_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Global_btnSearch {
            get {
                return ResourceManager.GetString("Global_btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Global_btnSend {
            get {
                return ResourceManager.GetString("Global_btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar solicitud de amistad.
        /// </summary>
        public static string Global_btnSendFriendRequest {
            get {
                return ResourceManager.GetString("Global_btnSendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar reporte.
        /// </summary>
        public static string Global_btnSendReport {
            get {
                return ResourceManager.GetString("Global_btnSendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Global_btnSettings {
            get {
                return ResourceManager.GetString("Global_btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        public static string Global_fmtShortDate {
            get {
                return ResourceManager.GetString("Global_fmtShortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles adicionales:.
        /// </summary>
        public static string Global_lblAdditionalDetails {
            get {
                return ResourceManager.GetString("Global_lblAdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string Global_lblChat {
            get {
                return ResourceManager.GetString("Global_lblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string Global_lblConfirmPassword {
            get {
                return ResourceManager.GetString("Global_lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Global_lblDate {
            get {
                return ResourceManager.GetString("Global_lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decisión.
        /// </summary>
        public static string Global_lblDecision {
            get {
                return ResourceManager.GetString("Global_lblDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Global_lblEmail {
            get {
                return ResourceManager.GetString("Global_lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no puede estar vacío.
        /// </summary>
        public static string Global_lblEmailRequired {
            get {
                return ResourceManager.GetString("Global_lblEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuaciones finales.
        /// </summary>
        public static string Global_lblFinalScores {
            get {
                return ResourceManager.GetString("Global_lblFinalScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes amigos agregados.
        /// </summary>
        public static string Global_lblNoFriends {
            get {
                return ResourceManager.GetString("Global_lblNoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectados.
        /// </summary>
        public static string Global_lblOffline {
            get {
                return ResourceManager.GetString("Global_lblOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En línea.
        /// </summary>
        public static string Global_lblOnline {
            get {
                return ResourceManager.GetString("Global_lblOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        public static string Global_lblParticipants {
            get {
                return ResourceManager.GetString("Global_lblParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Global_lblPassword {
            get {
                return ResourceManager.GetString("Global_lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía.
        /// </summary>
        public static string Global_lblPasswordRequired {
            get {
                return ResourceManager.GetString("Global_lblPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Global_lblPlayers {
            get {
                return ResourceManager.GetString("Global_lblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        public static string Global_lblReason {
            get {
                return ResourceManager.GetString("Global_lblReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        public static string Global_lblScore {
            get {
                return ResourceManager.GetString("Global_lblScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string Global_lblWinner {
            get {
                return ResourceManager.GetString("Global_lblWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un mensaje....
        /// </summary>
        public static string Global_txtChatPlaceholder {
            get {
                return ResourceManager.GetString("Global_txtChatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string HomePage_btnGuest {
            get {
                return ResourceManager.GetString("HomePage_btnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por un turno, no se puede colocar otra ficha y los puntos de ese extremo no se suman..
        /// </summary>
        public static string HowToPlay_lblBlockEnd {
            get {
                return ResourceManager.GetString("HowToPlay_lblBlockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloquea un extremo.
        /// </summary>
        public static string HowToPlay_lblBlockEndTitle {
            get {
                return ResourceManager.GetString("HowToPlay_lblBlockEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de sumar múltiplo de 5..
        /// </summary>
        public static string HowToPlay_lblDoublePoints {
            get {
                return ResourceManager.GetString("HowToPlay_lblDoublePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos dobles.
        /// </summary>
        public static string HowToPlay_lblDoublePointsTitle {
            get {
                return ResourceManager.GetString("HowToPlay_lblDoublePointsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para colocar una ficha, uno de los dos lados de la ficha debe tener los mismos puntos que algún extremo.
        /// </summary>
        public static string HowToPlay_lblPlaceTile {
            get {
                return ResourceManager.GetString("HowToPlay_lblPlaceTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas del juego.
        /// </summary>
        public static string HowToPlay_lblRules {
            get {
                return ResourceManager.GetString("HowToPlay_lblRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si los extremos de las fichas del tablero suman un múltiplo de 5. ¡Se suma esa cantidad a tu puntaje!.
        /// </summary>
        public static string HowToPlay_lblScoreMultipleFive {
            get {
                return ResourceManager.GetString("HowToPlay_lblScoreMultipleFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo jugar?.
        /// </summary>
        public static string HowToPlay_lblTitle {
            get {
                return ResourceManager.GetString("HowToPlay_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comodines.
        /// </summary>
        public static string HowToPlay_lblWildcards {
            get {
                return ResourceManager.GetString("HowToPlay_lblWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El primero en llegar a la puntuación ganadora, ¡gana toda la partida!.
        /// </summary>
        public static string HowToPlay_lblWinningScore {
            get {
                return ResourceManager.GetString("HowToPlay_lblWinningScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar a sala.
        /// </summary>
        public static string InviteFriends_btnInvite {
            get {
                return ResourceManager.GetString("InviteFriends_btnInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar invitación.
        /// </summary>
        public static string JoinGame_btnAcceptInvitation {
            get {
                return ResourceManager.GetString("JoinGame_btnAcceptInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitaciones.
        /// </summary>
        public static string JoinGame_btnInvitations {
            get {
                return ResourceManager.GetString("JoinGame_btnInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse por código.
        /// </summary>
        public static string JoinGame_btnJoinByCode {
            get {
                return ResourceManager.GetString("JoinGame_btnJoinByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string JoinGame_btnJoinRoom {
            get {
                return ResourceManager.GetString("JoinGame_btnJoinRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar el código de la sala.
        /// </summary>
        public static string JoinGame_lblEmptyRoomCode {
            get {
                return ResourceManager.GetString("JoinGame_lblEmptyRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de sala.
        /// </summary>
        public static string JoinGame_lblRoomCode {
            get {
                return ResourceManager.GetString("JoinGame_lblRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar amigos.
        /// </summary>
        public static string Lobby_btnInviteFriends {
            get {
                return ResourceManager.GetString("Lobby_btnInviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string Lobby_btnKick {
            get {
                return ResourceManager.GetString("Lobby_btnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar.
        /// </summary>
        public static string Lobby_btnReport {
            get {
                return ResourceManager.GetString("Lobby_btnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡A jugar!.
        /// </summary>
        public static string Lobby_btnStartGame {
            get {
                return ResourceManager.GetString("Lobby_btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver perfil.
        /// </summary>
        public static string Lobby_btnViewProfile {
            get {
                return ResourceManager.GetString("Lobby_btnViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de la sala.
        /// </summary>
        public static string Lobby_lblRoomCode {
            get {
                return ResourceManager.GetString("Lobby_lblRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando partida.
        /// </summary>
        public static string Lobby_lblStarting {
            get {
                return ResourceManager.GetString("Lobby_lblStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string Lobby_lblTitle {
            get {
                return ResourceManager.GetString("Lobby_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar código al portapapeles.
        /// </summary>
        public static string Lobby_tooltipCopyCode {
            get {
                return ResourceManager.GetString("Lobby_tooltipCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string Login_btnCreateAccount {
            get {
                return ResourceManager.GetString("Login_btnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string Login_btnForgotPassword {
            get {
                return ResourceManager.GetString("Login_btnForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string MainMenu_btnCreateGame {
            get {
                return ResourceManager.GetString("MainMenu_btnCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenu_btnFriends {
            get {
                return ResourceManager.GetString("MainMenu_btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo jugar.
        /// </summary>
        public static string MainMenu_btnHowToPlay {
            get {
                return ResourceManager.GetString("MainMenu_btnHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string MainMenu_btnJoinGame {
            get {
                return ResourceManager.GetString("MainMenu_btnJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuaciones.
        /// </summary>
        public static string MainMenu_btnScores {
            get {
                return ResourceManager.GetString("MainMenu_btnScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver reportes.
        /// </summary>
        public static string MainMenu_btnViewReports {
            get {
                return ResourceManager.GetString("MainMenu_btnViewReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de partidas.
        /// </summary>
        public static string MatchHistory_lblTitle {
            get {
                return ResourceManager.GetString("MatchHistory_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimiento.
        /// </summary>
        public static string MatchReplay_lblMove {
            get {
                return ResourceManager.GetString("MatchReplay_lblMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida #{0} - Fecha: {1}.
        /// </summary>
        public static string MatchReportInfo_lblMatchItem {
            get {
                return ResourceManager.GetString("MatchReportInfo_lblMatchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta fue creada correctamente..
        /// </summary>
        public static string MessageAccount_msgAccountCreated {
            get {
                return ResourceManager.GetString("MessageAccount_msgAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta creada.
        /// </summary>
        public static string MessageAccount_msgAccountCreatedTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgAccountCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo crear la cuenta. Ocurrió un error. Intenta nuevamente..
        /// </summary>
        public static string MessageAccount_msgAccountCreationError {
            get {
                return ResourceManager.GetString("MessageAccount_msgAccountCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de cuenta fallida.
        /// </summary>
        public static string MessageAccount_msgAccountCreationErrorTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgAccountCreationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar tu cuenta?.
        /// </summary>
        public static string MessageAccount_msgConfirmElimination {
            get {
                return ResourceManager.GetString("MessageAccount_msgConfirmElimination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string MessageAccount_msgConfirmEliminationTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgConfirmEliminationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta.
        /// </summary>
        public static string MessageAccount_msgDeleteAccountTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgDeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya está asociado a una cuenta..
        /// </summary>
        public static string MessageAccount_msgEmailUsed {
            get {
                return ResourceManager.GetString("MessageAccount_msgEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo en uso.
        /// </summary>
        public static string MessageAccount_msgEmailUsedTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgEmailUsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible actualizar la contraseña en este momento. Ocurrió un error. Intenta nuevamente más tarde..
        /// </summary>
        public static string MessageAccount_msgErrorChangingPassword {
            get {
                return ResourceManager.GetString("MessageAccount_msgErrorChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cambiar contraseña.
        /// </summary>
        public static string MessageAccount_msgErrorChangingPasswordTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgErrorChangingPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden. Cambia la contraseña e intenta nuevamente..
        /// </summary>
        public static string MessageAccount_msgIncorrectPassword {
            get {
                return ResourceManager.GetString("MessageAccount_msgIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos no coinciden.
        /// </summary>
        public static string MessageAccount_msgIncorrectPasswordTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgIncorrectPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más datos no cumplen con el formato requerido..
        /// </summary>
        public static string MessageAccount_msgInvalidData {
            get {
                return ResourceManager.GetString("MessageAccount_msgInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos inválidos.
        /// </summary>
        public static string MessageAccount_msgInvalidDataTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgInvalidDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña fue actualizada correctamente..
        /// </summary>
        public static string MessageAccount_msgPasswordChanged {
            get {
                return ResourceManager.GetString("MessageAccount_msgPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña cambiada.
        /// </summary>
        public static string MessageAccount_msgPasswordChangedTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgPasswordChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener como mínimo 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial..
        /// </summary>
        public static string MessageAccount_msgUnsafePassword {
            get {
                return ResourceManager.GetString("MessageAccount_msgUnsafePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña insegura.
        /// </summary>
        public static string MessageAccount_msgUnsafePasswordTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgUnsafePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya está en uso..
        /// </summary>
        public static string MessageAccount_msgUsernameUsed {
            get {
                return ResourceManager.GetString("MessageAccount_msgUsernameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario en uso.
        /// </summary>
        public static string MessageAccount_msgUsernameUsedTitle {
            get {
                return ResourceManager.GetString("MessageAccount_msgUsernameUsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible iniciar sesión en este momento. Intenta nuevamente..
        /// </summary>
        public static string MessageAuthentication_msgConnectionError {
            get {
                return ResourceManager.GetString("MessageAuthentication_msgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de inicio de sesión.
        /// </summary>
        public static string MessageAuthentication_msgConnectionErrorTitle {
            get {
                return ResourceManager.GetString("MessageAuthentication_msgConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible iniciar sesión con esta cuenta..
        /// </summary>
        public static string MessageAuthentication_msgDisabledAccount {
            get {
                return ResourceManager.GetString("MessageAuthentication_msgDisabledAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta deshabilitada.
        /// </summary>
        public static string MessageAuthentication_msgDisabledAccountTitle {
            get {
                return ResourceManager.GetString("MessageAuthentication_msgDisabledAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o la contraseña son incorrectos..
        /// </summary>
        public static string MessageAuthentication_msgInvalidCredentials {
            get {
                return ResourceManager.GetString("MessageAuthentication_msgInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas.
        /// </summary>
        public static string MessageAuthentication_msgInvalidCredentialsTitle {
            get {
                return ResourceManager.GetString("MessageAuthentication_msgInvalidCredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú y {0} ya son amigos..
        /// </summary>
        public static string MessageFriends_msgAlreadyFriends {
            get {
                return ResourceManager.GetString("MessageFriends_msgAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amistad existente.
        /// </summary>
        public static string MessageFriends_msgAlreadyFriendsTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgAlreadyFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar a {0} de tu lista de amigos?.
        /// </summary>
        public static string MessageFriends_msgDeleteFriend {
            get {
                return ResourceManager.GetString("MessageFriends_msgDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas cancelar la solicitud de amistad para {0}?.
        /// </summary>
        public static string MessageFriends_msgDeleteFriendRequest {
            get {
                return ResourceManager.GetString("MessageFriends_msgDeleteFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar solicitud de amistad.
        /// </summary>
        public static string MessageFriends_msgDeleteFriendRequestTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgDeleteFriendRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar amigo.
        /// </summary>
        public static string MessageFriends_msgDeleteFriendTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgDeleteFriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar la solicitud de amistad. Ocurrió un error. Intenta nuevamente..
        /// </summary>
        public static string MessageFriends_msgErrorFriendRequest {
            get {
                return ResourceManager.GetString("MessageFriends_msgErrorFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de solicitud.
        /// </summary>
        public static string MessageFriends_msgErrorFriendRequestTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgErrorFriendRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al establecer la amistad. Intenta nuevamente..
        /// </summary>
        public static string MessageFriends_msgErrorFriendship {
            get {
                return ResourceManager.GetString("MessageFriends_msgErrorFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al establecer la amistad.
        /// </summary>
        public static string MessageFriends_msgErrorFriendshipTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgErrorFriendshipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador fue agregado correctamente..
        /// </summary>
        public static string MessageFriends_msgFriendAdded {
            get {
                return ResourceManager.GetString("MessageFriends_msgFriendAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador agregado.
        /// </summary>
        public static string MessageFriends_msgFriendAddedTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgFriendAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has alcanzado el límite máximo de 99 amigos. Elimina un amigo para aceptar nuevas solicitudes..
        /// </summary>
        public static string MessageFriends_msgFriendLimit {
            get {
                return ResourceManager.GetString("MessageFriends_msgFriendLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite de amigos.
        /// </summary>
        public static string MessageFriends_msgFriendLimitTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgFriendLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora tú y {0} son amigos..
        /// </summary>
        public static string MessageFriends_msgFriendship {
            get {
                return ResourceManager.GetString("MessageFriends_msgFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva amistad.
        /// </summary>
        public static string MessageFriends_msgFriendshipTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgFriendshipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible cargar la lista de amigos..
        /// </summary>
        public static string MessageFriends_msgLoadFriendsError {
            get {
                return ResourceManager.GetString("MessageFriends_msgLoadFriendsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar amigos.
        /// </summary>
        public static string MessageFriends_msgLoadFriendsErrorTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgLoadFriendsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible cargar las solicitudes de amistad..
        /// </summary>
        public static string MessageFriends_msgLoadRequestsError {
            get {
                return ResourceManager.GetString("MessageFriends_msgLoadRequestsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar solicitudes.
        /// </summary>
        public static string MessageFriends_msgLoadRequestsErrorTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgLoadRequestsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes enviar una solicitud de amistad a ti mismo..
        /// </summary>
        public static string MessageFriends_msgOwnRequest {
            get {
                return ResourceManager.GetString("MessageFriends_msgOwnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud a sí mismo.
        /// </summary>
        public static string MessageFriends_msgOwnRequestTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgOwnRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes una solicitud de amistad de este jugador..
        /// </summary>
        public static string MessageFriends_msgPendingFriendRequest {
            get {
                return ResourceManager.GetString("MessageFriends_msgPendingFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud pendiente.
        /// </summary>
        public static string MessageFriends_msgPendingFriendRequestTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgPendingFriendRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible aceptar la solicitud porque el jugador alcanzó el límite de amigos..
        /// </summary>
        public static string MessageFriends_msgRequesterLimit {
            get {
                return ResourceManager.GetString("MessageFriends_msgRequesterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya has enviado una solicitud de amistad a este jugador..
        /// </summary>
        public static string MessageFriends_msgSentFriendRequest {
            get {
                return ResourceManager.GetString("MessageFriends_msgSentFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud existente.
        /// </summary>
        public static string MessageFriends_msgSentFriendRequestTitle {
            get {
                return ResourceManager.GetString("MessageFriends_msgSentFriendRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} tomó del pozo.
        /// </summary>
        public static string MessageGameplay_msgDrewFromBoneyard {
            get {
                return ResourceManager.GetString("MessageGameplay_msgDrewFromBoneyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin del juego.
        /// </summary>
        public static string MessageGameplay_msgGameEnd {
            get {
                return ResourceManager.GetString("MessageGameplay_msgGameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} pasó de turno.
        /// </summary>
        public static string MessageGameplay_msgPassTurn {
            get {
                return ResourceManager.GetString("MessageGameplay_msgPassTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de la ronda.
        /// </summary>
        public static string MessageGameplay_msgRoundEnd {
            get {
                return ResourceManager.GetString("MessageGameplay_msgRoundEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar por par mayor.
        /// </summary>
        public static string MessageGameplay_msgStartHighestDouble {
            get {
                return ResourceManager.GetString("MessageGameplay_msgStartHighestDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia por puntaje mayor.
        /// </summary>
        public static string MessageGameplay_msgStartHighestScore {
            get {
                return ResourceManager.GetString("MessageGameplay_msgStartHighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string MessageGeneral_msgErrorTitle {
            get {
                return ResourceManager.GetString("MessageGeneral_msgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya invitaste a este jugador a la sala..
        /// </summary>
        public static string MessageLobby_msgAlreadyInvited {
            get {
                return ResourceManager.GetString("MessageLobby_msgAlreadyInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador ya invitado.
        /// </summary>
        public static string MessageLobby_msgAlreadyInvitedTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgAlreadyInvitedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si sales de la sala, esta se cerrará. ¿Estás seguro de que deseas salir?.
        /// </summary>
        public static string MessageLobby_msgCloseLobby {
            get {
                return ResourceManager.GetString("MessageLobby_msgCloseLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de la sala.
        /// </summary>
        public static string MessageLobby_msgCloseLobbyTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgCloseLobbyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible invitar por correo. Ocurrió un error con el servicio. Intenta nuevamente..
        /// </summary>
        public static string MessageLobby_msgEmailInvitationFailed {
            get {
                return ResourceManager.GetString("MessageLobby_msgEmailInvitationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al invitar por correo.
        /// </summary>
        public static string MessageLobby_msgEmailInvitationFailedTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgEmailInvitationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible invitar al jugador. Intenta nuevamente..
        /// </summary>
        public static string MessageLobby_msgInvitationFailed {
            get {
                return ResourceManager.GetString("MessageLobby_msgInvitationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al invitar.
        /// </summary>
        public static string MessageLobby_msgInvitationFailedTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgInvitationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas expulsar a {0} de la sala?.
        /// </summary>
        public static string MessageLobby_msgKick {
            get {
                return ResourceManager.GetString("MessageLobby_msgKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo expulsar al jugador. Intenta nuevamente..
        /// </summary>
        public static string MessageLobby_msgKickFailedBody {
            get {
                return ResourceManager.GetString("MessageLobby_msgKickFailedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsión fallida.
        /// </summary>
        public static string MessageLobby_msgKickFailedTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgKickFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsión.
        /// </summary>
        public static string MessageLobby_msgKickTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgKickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay suficientes jugadores para iniciar la partida..
        /// </summary>
        public static string MessageLobby_msgNotEnoughPlayers {
            get {
                return ResourceManager.GetString("MessageLobby_msgNotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin jugadores suficientes.
        /// </summary>
        public static string MessageLobby_msgNotEnoughPlayersTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgNotEnoughPlayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas iniciar la partida?.
        /// </summary>
        public static string MessageLobby_msgStart {
            get {
                return ResourceManager.GetString("MessageLobby_msgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible iniciar la partida. Intenta nuevamente..
        /// </summary>
        public static string MessageLobby_msgStartError {
            get {
                return ResourceManager.GetString("MessageLobby_msgStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar partida.
        /// </summary>
        public static string MessageLobby_msgStartErrorTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgStartErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida.
        /// </summary>
        public static string MessageLobby_msgStartTitle {
            get {
                return ResourceManager.GetString("MessageLobby_msgStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo guardar la foto de perfil. Ocurrió un error. Intenta nuevamente más tarde..
        /// </summary>
        public static string MessageProfile_msgPhotoCannotBeUploaded {
            get {
                return ResourceManager.GetString("MessageProfile_msgPhotoCannotBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al subir foto.
        /// </summary>
        public static string MessageProfile_msgPhotoCannotBeUploadedTitle {
            get {
                return ResourceManager.GetString("MessageProfile_msgPhotoCannotBeUploadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo seleccionado no tiene un formato válido para la foto de perfil..
        /// </summary>
        public static string MessageProfile_msgPhotoInvalidFormat {
            get {
                return ResourceManager.GetString("MessageProfile_msgPhotoInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de perfil inválida.
        /// </summary>
        public static string MessageProfile_msgPhotoInvalidFormatTitle {
            get {
                return ResourceManager.GetString("MessageProfile_msgPhotoInvalidFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de la foto excede el límite permitido de 1 MB. Intenta con una foto más pequeña..
        /// </summary>
        public static string MessageProfile_msgPhotoTooLarge {
            get {
                return ResourceManager.GetString("MessageProfile_msgPhotoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño del archivo.
        /// </summary>
        public static string MessageProfile_msgPhotoTooLargeTitle {
            get {
                return ResourceManager.GetString("MessageProfile_msgPhotoTooLargeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible consultar el perfil. Intenta nuevamente..
        /// </summary>
        public static string MessageProfile_msgProfileError {
            get {
                return ResourceManager.GetString("MessageProfile_msgProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de consulta.
        /// </summary>
        public static string MessageProfile_msgProfileErrorTitle {
            get {
                return ResourceManager.GetString("MessageProfile_msgProfileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible guardar los cambios en este momento. Intenta nuevamente..
        /// </summary>
        public static string MessageProfile_msgUpdateProfileError {
            get {
                return ResourceManager.GetString("MessageProfile_msgUpdateProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar.
        /// </summary>
        public static string MessageProfile_msgUpdateProfileErrorTitle {
            get {
                return ResourceManager.GetString("MessageProfile_msgUpdateProfileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo recuperar la evidencia asociada al reporte. Ocurrió un error al consultarla. Intenta nuevamente..
        /// </summary>
        public static string MessageReports_msgEvidenceRetrievalError {
            get {
                return ResourceManager.GetString("MessageReports_msgEvidenceRetrievalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al recuperar evidencia.
        /// </summary>
        public static string MessageReports_msgEvidenceRetrievalErrorTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgEvidenceRetrievalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar tu reporte. Ya has reportado esta partida..
        /// </summary>
        public static string MessageReports_msgMatchAlreadyReported {
            get {
                return ResourceManager.GetString("MessageReports_msgMatchAlreadyReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida ya reportada.
        /// </summary>
        public static string MessageReports_msgMatchAlreadyReportedTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgMatchAlreadyReportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar tu reporte. Debes seleccionar un motivo antes de enviarlo. Intenta nuevamente..
        /// </summary>
        public static string MessageReports_msgNoReason {
            get {
                return ResourceManager.GetString("MessageReports_msgNoReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin motivo.
        /// </summary>
        public static string MessageReports_msgNoReasonTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgNoReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar tu reporte. Ya has reportado a este jugador en esta partida..
        /// </summary>
        public static string MessageReports_msgPlayerAlreadyReported {
            get {
                return ResourceManager.GetString("MessageReports_msgPlayerAlreadyReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador ya reportado.
        /// </summary>
        public static string MessageReports_msgPlayerAlreadyReportedTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgPlayerAlreadyReportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha registrado la respuesta al reporte #{0}..
        /// </summary>
        public static string MessageReports_msgReportResolved {
            get {
                return ResourceManager.GetString("MessageReports_msgReportResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte atendido.
        /// </summary>
        public static string MessageReports_msgReportResolvedTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgReportResolvedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo recuperar la información del reporte. Ocurrió un error al consultarla. Intenta nuevamente..
        /// </summary>
        public static string MessageReports_msgReportRetrievalError {
            get {
                return ResourceManager.GetString("MessageReports_msgReportRetrievalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al recuperar reporte.
        /// </summary>
        public static string MessageReports_msgReportRetrievalErrorTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgReportRetrievalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar tu reporte. Ocurrió un error al intentar registrarlo. Intenta nuevamente..
        /// </summary>
        public static string MessageReports_msgReportSendError {
            get {
                return ResourceManager.GetString("MessageReports_msgReportSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar reporte.
        /// </summary>
        public static string MessageReports_msgReportSendErrorTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgReportSendErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu reporte se ha enviado. Un moderador lo revisará más tarde..
        /// </summary>
        public static string MessageReports_msgReportSent {
            get {
                return ResourceManager.GetString("MessageReports_msgReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte enviado.
        /// </summary>
        public static string MessageReports_msgReportSentTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgReportSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo registrar la respuesta del reporte. Ocurrió un error al guardarla. Intenta nuevamente..
        /// </summary>
        public static string MessageReports_msgResolutionSaveError {
            get {
                return ResourceManager.GetString("MessageReports_msgResolutionSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar resolución.
        /// </summary>
        public static string MessageReports_msgResolutionSaveErrorTitle {
            get {
                return ResourceManager.GetString("MessageReports_msgResolutionSaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error y no se pudo crear la sala..
        /// </summary>
        public static string MessageRooms_msgErrorCreateGame {
            get {
                return ResourceManager.GetString("MessageRooms_msgErrorCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear partida.
        /// </summary>
        public static string MessageRooms_msgErrorCreateGameTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgErrorCreateGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo unir a la partida. Ocurrió un error. Intenta nuevamente..
        /// </summary>
        public static string MessageRooms_msgErrorJoiningRoom {
            get {
                return ResourceManager.GetString("MessageRooms_msgErrorJoiningRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al unirse a partida.
        /// </summary>
        public static string MessageRooms_msgErrorJoiningRoomTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgErrorJoiningRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes unirte a esta sala porque has sido expulsado previamente..
        /// </summary>
        public static string MessageRooms_msgPreviouslyKicked {
            get {
                return ResourceManager.GetString("MessageRooms_msgPreviouslyKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsado.
        /// </summary>
        public static string MessageRooms_msgPreviouslyKickedTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgPreviouslyKickedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo unir a la partida. Otro jugador ocupó el último cupo..
        /// </summary>
        public static string MessageRooms_msgRoomCapacity {
            get {
                return ResourceManager.GetString("MessageRooms_msgRoomCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite de jugadores de la sala.
        /// </summary>
        public static string MessageRooms_msgRoomCapacityTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgRoomCapacityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo unir a la sala. Se alcanzó el límite de jugadores para esta sala..
        /// </summary>
        public static string MessageRooms_msgRoomFull {
            get {
                return ResourceManager.GetString("MessageRooms_msgRoomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala llena.
        /// </summary>
        public static string MessageRooms_msgRoomFullTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgRoomFullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible unirse a la sala. No se encontró una sala que coincida con el código ingresado..
        /// </summary>
        public static string MessageRooms_msgRoomNotFound {
            get {
                return ResourceManager.GetString("MessageRooms_msgRoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala no encontrada.
        /// </summary>
        public static string MessageRooms_msgRoomNotFoundTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgRoomNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible unirse a la sala. El código expiró o la partida ya inició..
        /// </summary>
        public static string MessageRooms_msgUnavailableRoom {
            get {
                return ResourceManager.GetString("MessageRooms_msgUnavailableRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala no disponible.
        /// </summary>
        public static string MessageRooms_msgUnavailableRoomTitle {
            get {
                return ResourceManager.GetString("MessageRooms_msgUnavailableRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas cerrar sesión?.
        /// </summary>
        public static string MessageSettings_msgConfirmLogout {
            get {
                return ResourceManager.GetString("MessageSettings_msgConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya está registrado..
        /// </summary>
        public static string MessageSettings_msgEmailDuplicate {
            get {
                return ResourceManager.GetString("MessageSettings_msgEmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico fue actualizado correctamente..
        /// </summary>
        public static string MessageSettings_msgEmailUpdated {
            get {
                return ResourceManager.GetString("MessageSettings_msgEmailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible actualizar el correo electrónico..
        /// </summary>
        public static string MessageSettings_msgEmailUpdateError {
            get {
                return ResourceManager.GetString("MessageSettings_msgEmailUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado no tiene un formato válido..
        /// </summary>
        public static string MessageSettings_msgInvalidEmail {
            get {
                return ResourceManager.GetString("MessageSettings_msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código expiró. Puedes reenviar un código nuevo a tu correo..
        /// </summary>
        public static string MessageVerification_msgAttemptsExceeded {
            get {
                return ResourceManager.GetString("MessageVerification_msgAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos agotados.
        /// </summary>
        public static string MessageVerification_msgAttemptsExceededTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgAttemptsExceededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió un código de verificación al correo electrónico..
        /// </summary>
        public static string MessageVerification_msgCodeSent {
            get {
                return ResourceManager.GetString("MessageVerification_msgCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código enviado.
        /// </summary>
        public static string MessageVerification_msgCodeSentTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgCodeSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudimos enviar el código. Ocurrió un error al enviarlo. Intenta nuevamente..
        /// </summary>
        public static string MessageVerification_msgEmailServiceError {
            get {
                return ResourceManager.GetString("MessageVerification_msgEmailServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar correo.
        /// </summary>
        public static string MessageVerification_msgEmailServiceErrorTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgEmailServiceErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ha sido verificado correctamente..
        /// </summary>
        public static string MessageVerification_msgEmailVerified {
            get {
                return ResourceManager.GetString("MessageVerification_msgEmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo verificado.
        /// </summary>
        public static string MessageVerification_msgEmailVerifiedTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgEmailVerifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación ha expirado..
        /// </summary>
        public static string MessageVerification_msgExpiredCode {
            get {
                return ResourceManager.GetString("MessageVerification_msgExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código expirado.
        /// </summary>
        public static string MessageVerification_msgExpiredCodeTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgExpiredCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación no es válido..
        /// </summary>
        public static string MessageVerification_msgInvalidCode {
            get {
                return ResourceManager.GetString("MessageVerification_msgInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código inválido.
        /// </summary>
        public static string MessageVerification_msgInvalidCodeTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgInvalidCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error con la información del código de verificación. Intenta nuevamente..
        /// </summary>
        public static string MessageVerification_msgVerificationCodeError {
            get {
                return ResourceManager.GetString("MessageVerification_msgVerificationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con el código.
        /// </summary>
        public static string MessageVerification_msgVerificationCodeErrorTitle {
            get {
                return ResourceManager.GetString("MessageVerification_msgVerificationCodeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver historial del chat.
        /// </summary>
        public static string PlayerReportInfo_btnViewChatHistory {
            get {
                return ResourceManager.GetString("PlayerReportInfo_btnViewChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de partidas.
        /// </summary>
        public static string Profile_btnMatchHistory {
            get {
                return ResourceManager.GetString("Profile_btnMatchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas jugadas.
        /// </summary>
        public static string Profile_lblGamesPlayed {
            get {
                return ResourceManager.GetString("Profile_lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Profile_lblTitle {
            get {
                return ResourceManager.GetString("Profile_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos totales.
        /// </summary>
        public static string Profile_lblTotalPoints {
            get {
                return ResourceManager.GetString("Profile_lblTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victorias.
        /// </summary>
        public static string Profile_lblWins {
            get {
                return ResourceManager.GetString("Profile_lblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking de partidas ganadas.
        /// </summary>
        public static string Rankings_lblTitle {
            get {
                return ResourceManager.GetString("Rankings_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu ranking:.
        /// </summary>
        public static string Rankings_lblYourRank {
            get {
                return ResourceManager.GetString("Rankings_lblYourRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código de verificación.
        /// </summary>
        public static string RecoverAccount_btnSendVerificationCode {
            get {
                return ResourceManager.GetString("RecoverAccount_btnSendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar cuenta.
        /// </summary>
        public static string RecoverAccount_lblTitle {
            get {
                return ResourceManager.GetString("RecoverAccount_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string RegisterAccount_btnRegister {
            get {
                return ResourceManager.GetString("RegisterAccount_btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string RegisterAccount_lblTitle {
            get {
                return ResourceManager.GetString("RegisterAccount_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string RegisterAccount_lblUsername {
            get {
                return ResourceManager.GetString("RegisterAccount_lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no puede estar vacío.
        /// </summary>
        public static string RegisterAccount_lblUsernameRequired {
            get {
                return ResourceManager.GetString("RegisterAccount_lblUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar partida.
        /// </summary>
        public static string ReportMatch_lblTitle {
            get {
                return ResourceManager.GetString("ReportMatch_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trampas.
        /// </summary>
        public static string ReportPlayer_btnCheating {
            get {
                return ResourceManager.GetString("ReportPlayer_btnCheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comportamiento inapropiado.
        /// </summary>
        public static string ReportPlayer_btnInappropriateBehavior {
            get {
                return ResourceManager.GetString("ReportPlayer_btnInappropriateBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar jugador.
        /// </summary>
        public static string ReportPlayer_lblTitle {
            get {
                return ResourceManager.GetString("ReportPlayer_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas.
        /// </summary>
        public static string Reports_btnMatches {
            get {
                return ResourceManager.GetString("Reports_btnMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver reporte.
        /// </summary>
        public static string Reports_btnViewReport {
            get {
                return ResourceManager.GetString("Reports_btnViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string Reports_lblTitle {
            get {
                return ResourceManager.GetString("Reports_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida inválida.
        /// </summary>
        public static string ResolveMatchReport_btnInvalidMatch {
            get {
                return ResourceManager.GetString("ResolveMatchReport_btnInvalidMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida válida.
        /// </summary>
        public static string ResolveMatchReport_btnValidMatch {
            get {
                return ResourceManager.GetString("ResolveMatchReport_btnValidMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banear jugador.
        /// </summary>
        public static string ResolvePlayerReport_btnBan {
            get {
                return ResourceManager.GetString("ResolvePlayerReport_btnBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hacer nada.
        /// </summary>
        public static string ResolvePlayerReport_btnDoNothing {
            get {
                return ResourceManager.GetString("ResolvePlayerReport_btnDoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suspensión.
        /// </summary>
        public static string ResolvePlayerReport_btnSuspend {
            get {
                return ResourceManager.GetString("ResolvePlayerReport_btnSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días:.
        /// </summary>
        public static string ResolvePlayerReport_lblDays {
            get {
                return ResourceManager.GetString("ResolvePlayerReport_lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string Settings_btnAccount {
            get {
                return ResourceManager.GetString("Settings_btnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string Settings_btnChange {
            get {
                return ResourceManager.GetString("Settings_btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta.
        /// </summary>
        public static string Settings_btnDeleteAccount {
            get {
                return ResourceManager.GetString("Settings_btnDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Settings_btnLanguage {
            get {
                return ResourceManager.GetString("Settings_btnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Settings_btnLogout {
            get {
                return ResourceManager.GetString("Settings_btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Settings_lblTitle {
            get {
                return ResourceManager.GetString("Settings_lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string UploadProfilePicture_btnAddPhoto {
            get {
                return ResourceManager.GetString("UploadProfilePicture_btnAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Omitir.
        /// </summary>
        public static string UploadProfilePicture_btnSkipPhoto {
            get {
                return ResourceManager.GetString("UploadProfilePicture_btnSkipPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona foto de perfil.
        /// </summary>
        public static string UploadProfilePicture_lblInstruction {
            get {
                return ResourceManager.GetString("UploadProfilePicture_lblInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de perfil.
        /// </summary>
        public static string UploadProfilePicture_lblProfilePhoto {
            get {
                return ResourceManager.GetString("UploadProfilePicture_lblProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        public static string VerifyEmail_btnResend {
            get {
                return ResourceManager.GetString("VerifyEmail_btnResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar.
        /// </summary>
        public static string VerifyEmail_btnVerify {
            get {
                return ResourceManager.GetString("VerifyEmail_btnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación.
        /// </summary>
        public static string VerifyEmail_lblCode {
            get {
                return ResourceManager.GetString("VerifyEmail_lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar correo.
        /// </summary>
        public static string VerifyEmail_lblTitle {
            get {
                return ResourceManager.GetString("VerifyEmail_lblTitle", resourceCulture);
            }
        }
    }
}
