//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DominoAllFivesEntities : DbContext
    {
        public DominoAllFivesEntities()
            : base("name=DominoAllFivesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FriendRequest> FriendRequest { get; set; }
        public virtual DbSet<GameInvitation> GameInvitation { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<MatchHistory> MatchHistory { get; set; }
        public virtual DbSet<MatchParticipant> MatchParticipant { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerStats> PlayerStats { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<VerificationCode> VerificationCode { get; set; }
    }
}
