//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int IdFriendRequest { get; set; }
        public int IdSender { get; set; }
        public int IdReceiver { get; set; }
        public string State { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
