//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchParticipant
    {
        public int IdGame { get; set; }
        public int IdPlayer { get; set; }
        public short Score { get; set; }
        public Nullable<byte> Position { get; set; }
        public bool WasKicked { get; set; }
    
        public virtual MatchHistory MatchHistory { get; set; }
        public virtual Player Player { get; set; }
    }
}
