//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStats
    {
        public int IdPlayer { get; set; }
        public int GamesWon { get; set; }
        public int GamesPlayed { get; set; }
        public int TotalPointsScored { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
