//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int IdReport { get; set; }
        public int IdReporter { get; set; }
        public Nullable<int> IdReportedPlayer { get; set; }
        public Nullable<int> IdGame { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string AdditionalInfo { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual MatchHistory MatchHistory { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
