//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoAllFives.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationCode
    {
        public int IdVerificationCode { get; set; }
        public string TargetEmail { get; set; }
        public string CodeHash { get; set; }
        public string Purpose { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public bool IsUsed { get; set; }
        public int AttemptCount { get; set; }
        public Nullable<int> IdPlayer { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
